START_APP: "App started"
END_APP: "App ended"
LOGGED_IN: "Logged in succesfully with %s"
VERIFY_USERNAME: "Verifying username"
CREATE_ACCOUNT: "Creating account"
GENERATE_TOKENS: "Generating tokens"
REFRESH_INITIATE: "Refresh Initiated"
NEW_TOKEN: "New access token generated"
LOGOUT_INITIATE: "Logout Initiated"
FETCH_ROLE_ID: "Fetching role and user_id"
