WELCOME_MESSAGE : "WELCOME TO WeatherView!"

ENTER_USERNAME : "Enter username: "

ENTER_PASSWORD : "Enter password: "

ENTER_CITY : "Enter your city: "

ENTER_ZIPCODE : "Enter zipcode: "

DATABASE_NAME : 'data.db'

LOGIN_ADMIN : "LOGGED IN AS ADMIN...\n"

LOGIN_USER : "LOGGED IN AS USER...\n"

INVALID_INPUT : "INVALID INPUT. PLEASE TRY AGAIN...\n"

USERNAME_ERROR : "USERNAME ALREADY TAKEN. PLEASE ENTER NEW USERNAME...\n"

INVALID_CREDENTIALS : "INVALID CREDENTIALS. PLEASE TRY AGAIN!\n"